name: Build tweak - 2 DEBs
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Tweak
        run: |
          # your build command here
          # example: make package

# ========== GENERATE .plist ==========
      - name: Generate .plist
        run: |
          cat > YTKACE.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>Filter</key>
              <dict>
                  <key>Bundles</key>
                  <array>
                      <string>com.google.ios.youtube</string>
                  </array>
              </dict>
          </dict>
          </plist>
          EOF

      # ========== UNZIP BUNDLE ==========
      - name: Unzip bundle
        run: |
          unzip YTKACE.bundle.zip -d .
          # outputs: .bundle/

      # ========== ROOTFUL - arm | dylib + bundle ==========
      - name: Create Rootful structure
        run: |
          mkdir -p tweak-rootful/DEBIAN
          mkdir -p tweak-rootful/Library/MobileSubstrate/DynamicLibraries
          mkdir -p tweak-rootful/Library/Application\ Support/ytkace

      - name: Copy files Rootful
        run: |
          cp YTKACE.dylib tweak-rootful/Library/MobileSubstrate/DynamicLibraries/
          cp YTKACE.plist tweak-rootful/Library/MobileSubstrate/DynamicLibraries/
          cp -r YTKACE.bundle tweak-rootful/Library/Application\ Support/ytkace/

      - name: Create control Rootful
        run: |
          cat > tweak-rootful/DEBIAN/control << EOF
          Package: com.youtube.ytkace
          Name: YTKACE (rootfull)
          Version: 0.6.4
          Architecture: iphoneos-arm
          Description: yt tweak
          Maintainer: ace
          Section: Tweaks
          Depends: mobilesubstrate
          EOF

      - name: Build Rootful DEB
        run: dpkg-deb -b tweak-rootful ytkace_0.6.4_iphoneos-arm.deb

      # ========== ROOTLESS - arm64 | dylib + bundle ==========
      - name: Create Rootless structure
        run: |
          mkdir -p tweak-rootless/DEBIAN
          mkdir -p tweak-rootless/var/jb/Library/MobileSubstrate/DynamicLibraries
          mkdir -p tweak-rootless/var/jb/Library/Application\ Support/wgold

      - name: Copy files Rootless
        run: |
          cp YTKACE.dylib tweak-rootless/var/jb/Library/MobileSubstrate/DynamicLibraries/
          cp YTKACE.plist tweak-rootless/var/jb/Library/MobileSubstrate/DynamicLibraries/
          cp -r YTKACE.bundle tweak-rootless/var/jb/Library/Application\ Support/ytkace/

      - name: Create control Rootless
        run: |
          cat > tweak-rootless/DEBIAN/control << EOF
          Package: com.youtube.ytkace
          Name: YTKACE (Rootless)
          Version: 0.6.4
          Architecture: iphoneos-arm64
          Description: yt tweak - Rootless
          Maintainer: ace
          Section: Tweaks
          Depends: mobilesubstrate
          
      - name: Build Rootless DEB
        run: dpkg-deb -b tweak-rootless ytkace_0.6.4_rootless_iphoneos-arm64.deb

         # ========== UPLOAD 2 DEBS ==========
      - uses: actions/upload-artifact@v4
        with:
          name: tweak - rootfullrootless
          path: |
            ytkace_0.6.4_iphoneos-arm.deb
            ytkace_0.6.4_rootless_iphoneos-arm64.deb
